services:
  gammy_postgres:
    image: postgres:latest
    container_name: gammy-postgres
    restart: always
    environment:
      POSTGRES_USER: gammy
      POSTGRES_PASSWORD: gammypassword
      POSTGRES_DB: gammydb
    ports:
      - "5432:5432"
    volumes:
      - gammy_postgres_data:/var/lib/postgresql/data

  gammy_zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: gammy-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  gammy_kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: gammy-kafka
    depends_on:
      - gammy_postgres
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  gammy_postgres_data:
