services:
  gammy_postgres:
    image: postgres:latest
    container_name: gammy-postgres
    restart: always
    environment:
      POSTGRES_USER: gammy
      POSTGRES_PASSWORD: gammypassword
      POSTGRES_DB: gammydb
    ports:
      - "5432:5432"
    volumes:
      - gammy_postgres_data:/var/lib/postgresql/data
volumes:
  gammy_postgres_data:
