openapi: 3.0.1
info:
  title: gammy
  version: 1.0.0
paths:
  /achievements/game:
    get:
      operationId: getGameAchievements
      responses:
        "200":
          description: getGameAchievements 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GameAchievementEntity"
    put:
      operationId: updateAchievement
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GameAchievementEntity"
        required: true
      responses:
        "200":
          description: updateAchievement 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameAchievementEntity"
    post:
      operationId: createAchievement
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GameAchievementEntity"
        required: true
      responses:
        "200":
          description: createAchievement 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameAchievementEntity"
  /achievements/player/{playerId}:
    get:
      operationId: getAchievementStatusForPlayer
      parameters:
      - name: playerId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: getAchievementStatusForPlayer 200 response
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: boolean
  /achievements/player/{playerId}/{apiName}:
    post:
      operationId: unlockPlayerAchievement
      parameters:
      - name: playerId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: apiName
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: unlockPlayerAchievement 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlayerAchievementEntity"
    delete:
      operationId: removePlayerAchievement
      parameters:
      - name: playerId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: apiName
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: removePlayerAchievement 200 response
  /interactions/player/{playerId}:
    get:
      operationId: getPlayerInteractions
      parameters:
      - name: playerId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: getPlayerInteractions 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PlayerInteractionEntity"
  /interactions/track/{playerId}/{interactionApiName}:
    post:
      operationId: trackInteraction
      parameters:
      - name: playerId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: interactionApiName
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: trackInteraction 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlayerInteractionEntity"
  /interactions/type:
    get:
      operationId: getGameInteractions
      responses:
        "200":
          description: getGameInteractions 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GameInteractionEntity"
    put:
      operationId: updateGameInteraction
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GameInteractionEntity"
        required: true
      responses:
        "200":
          description: updateGameInteraction 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameInteractionEntity"
    post:
      operationId: createInteraction
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GameInteractionEntity"
        required: true
      responses:
        "200":
          description: createInteraction 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameInteractionEntity"
  /interactions/type/{apiName}:
    get:
      operationId: getInteractionsByApiName
      parameters:
      - name: apiName
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: getInteractionsByApiName 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PlayerInteractionEntity"
  /leaderboards:
    post:
      operationId: updateLeaderboard
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - $ref: "#/components/schemas/LeaderboardEntity"
              - $ref: "#/components/schemas/LeaderboardCreateRequest"
            example: null
        required: true
      responses:
        "200":
          description: updateLeaderboard 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LeaderboardEntity"
  /leaderboards/{apiName}:
    get:
      operationId: getLeaderboardEntries
      parameters:
      - name: apiName
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: getLeaderboardEntries 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LeaderboardEntries"
  /players:
    get:
      operationId: findAll
      responses:
        "200":
          description: findAll 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PlayerEntity"
    post:
      operationId: createPlayer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PlayerRegistrationRequest"
        required: true
      responses:
        "200":
          description: createPlayer 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlayerEntity"
  /reports:
    post:
      operationId: reportPlayer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReportPlayerRequest"
        required: true
      responses:
        "200":
          description: reportPlayer 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlayerReportEntity"
  /reports/by/{playerId}:
    get:
      operationId: getReportsBy
      parameters:
      - name: playerId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: getReportsBy 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PlayerReportEntity"
  /reports/for/{playerId}:
    get:
      operationId: getReportsFor
      parameters:
      - name: playerId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: getReportsFor 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PlayerReportEntity"
  /stats/game:
    get:
      operationId: getGameStats
      responses:
        "200":
          description: getGameStats 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GameStatEntity"
    put:
      operationId: updateGameStat
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GameStatEntity"
        required: true
      responses:
        "200":
          description: updateGameStat 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameStatEntity"
    post:
      operationId: createGameStat
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GameStatEntity"
        required: true
      responses:
        "200":
          description: createGameStat 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameStatEntity"
  /stats/player/{playerId}:
    get:
      operationId: getPlayerStats
      parameters:
      - name: playerId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: getPlayerStats 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PlayerStatEntity"
    post:
      operationId: updatePlayerStat
      parameters:
      - name: playerId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PlayerGameStatUpdateRequest"
        required: true
      responses:
        "200":
          description: updatePlayerStat 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlayerStatEntity"
  /stats/player/{playerId}/history:
    get:
      operationId: getPlayerStatHistory
      parameters:
      - name: playerId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: getPlayerStatHistory 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StatUpdateHistoryEntity"
  /stats/player/{playerId}/{statApiName}/history:
    get:
      operationId: getPlayerStatHistory_1
      parameters:
      - name: playerId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: statApiName
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: getPlayerStatHistory_1 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StatUpdateHistoryEntity"
  /user:
    get:
      operationId: me
      responses:
        "200":
          description: me 200 response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
components:
  schemas:
    GameAchievementEntity:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        name:
          type: string
        apiName:
          type: string
        description:
          type: string
        unlockExpression:
          type: string
          nullable: true
    GameInteractionEntity:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        apiName:
          type: string
        displayName:
          type: string
        streak:
          $ref: "#/components/schemas/GameInteractionStreak"
    GameInteractionStreak:
      type: string
      enum:
      - NONE
      - DAILY
    GameStatEntity:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        apiName:
          type: string
        displayName:
          type: string
        description:
          type: string
        type:
          $ref: "#/components/schemas/GameStatType"
        defaultValue:
          type: number
        maxValue:
          type: number
          nullable: true
        minValue:
          type: number
          nullable: true
        maxChange:
          type: number
          nullable: true
        onlyIncrement:
          type: boolean
    GameStatType:
      type: string
      enum:
      - INTEGER
      - FLOAT
    LeaderboardCreateRequest:
      type: object
      properties:
        displayName:
          type: string
        apiName:
          type: string
        description:
          type: string
        sortMethod:
          $ref: "#/components/schemas/LeaderboardSortMethod"
        gameStatApiName:
          type: string
    LeaderboardEntity:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        displayName:
          type: string
        apiName:
          type: string
        description:
          type: string
        sortMethod:
          $ref: "#/components/schemas/LeaderboardSortMethod"
        gameStat:
          $ref: "#/components/schemas/GameStatEntity"
    LeaderboardEntries:
      required:
      - entries
      - leaderboard
      type: object
      properties:
        leaderboard:
          $ref: "#/components/schemas/LeaderboardEntity"
        entries:
          type: array
          items:
            $ref: "#/components/schemas/LeaderboardEntry"
    LeaderboardEntry:
      required:
      - player
      - rank
      - value
      type: object
      properties:
        player:
          $ref: "#/components/schemas/PlayerEntity"
        value:
          type: number
        rank:
          type: integer
          format: int64
    LeaderboardSortMethod:
      type: string
      enum:
      - ASCENDING
      - DESCENDING
    PlayerAchievementEntity:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        gameAchievement:
          $ref: "#/components/schemas/GameAchievementEntity"
        player:
          $ref: "#/components/schemas/PlayerEntity"
        createdAt:
          type: string
          format: date-time
    PlayerEntity:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        username:
          type: string
        hashedPassword:
          type: string
    PlayerGameStatUpdateMethod:
      type: string
      enum:
      - LOWEST
      - LARGEST
      - FORCE
    PlayerGameStatUpdateRequest:
      type: object
      properties:
        gameStatApiName:
          type: string
        newValue:
          type: number
        updateMethod:
          $ref: "#/components/schemas/PlayerGameStatUpdateMethod"
    PlayerInteractionEntity:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        gameInteraction:
          $ref: "#/components/schemas/GameInteractionEntity"
        player:
          $ref: "#/components/schemas/PlayerEntity"
        timestamp:
          type: string
          format: date-time
        streak:
          type: integer
          format: int64
    PlayerRegistrationRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    PlayerReportEntity:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        reporterPlayer:
          nullable: true
          allOf:
          - $ref: "#/components/schemas/PlayerEntity"
        reportedPlayer:
          $ref: "#/components/schemas/PlayerEntity"
        text:
          type: string
    PlayerStatEntity:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        gameStat:
          $ref: "#/components/schemas/GameStatEntity"
        player:
          $ref: "#/components/schemas/PlayerEntity"
        value:
          type: number
        lastUpdate:
          type: string
          format: date-time
    ReportPlayerRequest:
      required:
      - reportedPlayerId
      - reporterPlayerId
      - text
      type: object
      properties:
        reporterPlayerId:
          type: integer
          format: int64
        reportedPlayerId:
          type: integer
          format: int64
        text:
          type: string
    StatUpdateHistoryEntity:
      required:
      - gameStat
      - id
      - newValue
      - oldValue
      - player
      - suspicious
      - timestamp
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        player:
          $ref: "#/components/schemas/PlayerEntity"
        gameStat:
          $ref: "#/components/schemas/GameStatEntity"
        oldValue:
          type: number
        newValue:
          type: number
        timestamp:
          type: string
          format: date-time
        suspicious:
          type: boolean
