liquibase:
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.xml

micronaut:
  application:
    name: gammy

  openapi:
    target:
      file: gammy-dashboard/spec.yml

  session:
    http:
      header: true
      cookie: true

  server:
    cors:
      enabled: true
      allowed-origins:
        - "http://localhost:5173"
      allowed-methods:
        - GET
        - POST
        - OPTIONS
        - PUT
        - DELETE
      allowed-headers:
        - Authorization
        - Content-Type
      allow-credentials: true

  security:
    enabled: true
    redirect:
      enabled: false
    csrf:
      enabled: false
    authentication: session
    session:
      enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
    intercept-url-map:
      - pattern: /login
        access:
          - isAnonymous()
      - pattern: /logout
        access:
          - isAuthenticated()
      - pattern: /profile/**
        access:
          - isAuthenticated()
      - pattern: /**
        http-method: OPTIONS
        access:
          - permitAll()
      - pattern: /**
        access:
          - permitAll()

  serde:
    serialization:
      inclusion: always

datasources:
  default:
    db-type: postgres
    driver-class-name: org.postgresql.Driver
    username: gammy
    password: gammypassword
    url: jdbc:postgresql://localhost:5432/gammydb

logger:
  io:
    micronaut:
      security: DEBUG
      http:
        server: DEBUG
