micronaut:
  application:
    name: gammy

  server:
    port: 8080
    cors:
      enabled: true
      allowed-origins:
        - "http://localhost:5173"
      allowed-methods:
        - GET
        - POST
        - OPTIONS
        - PUT
        - DELETE
      allowed-headers:
        - Authorization
        - Content-Type
      allow-credentials: true

  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true

  management:
    enabled: true
    endpoints:
      all:
        enabled: true
        sensitive: false
      metrics:
        enabled: true
        sensitive: false
      prometheus:
        enabled: true
        sensitive: false

  security:
    enabled: true
    reject-not-found: false
    csrf:
      enabled: false
    redirect:
      enabled: false
    authentication: session
    session:
      enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
    ignored:
      urls:
        - /metrics
        - /metrics/**
        - /prometheus
    intercept-url-map:
      - pattern: /login
        access:
          - isAnonymous()
      - pattern: /logout
        access:
          - isAuthenticated()
      - pattern: /profile/**
        access:
          - isAuthenticated()
      - pattern: /metrics
        access:
          - permitAll()
      - pattern: /metrics/**
        access:
          - permitAll()
      - pattern: /prometheus
        access:
          - permitAll()
      - pattern: /prometheus/**
        access:
          - permitAll()
      - pattern: /**
        http-method: OPTIONS
        access:
          - permitAll()
      - pattern: /**
        access:
          - permitAll()
      - pattern: /health
        access:
          - permitAll()

  openapi:
    target:
      file: gammy-dashboard/spec.yml

  session:
    http:
      header: true
      cookie: true

  serde:
    serialization:
      inclusion: always

liquibase:
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.xml

datasources:
  default:
    db-type: postgres
    driver-class-name: org.postgresql.Driver
    username: gammy
    password: gammypassword
    url: jdbc:postgresql://localhost:5432/gammydb

logger:
  io:
    micronaut:
      security: DEBUG
      http:
        server: DEBUG
